Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@AndrewAtCheckmarx 
CxUK
/
BookStore
Private
1
00
Code
Issues
Pull requests
Actions
Projects
Security
Insights
Settings
BookStore/.circleci/config.yml
@AndrewAtCheckmarx
AndrewAtCheckmarx Update config.yml
Latest commit f93981c 2 hours ago
 History
 1 contributor
48 lines (42 sloc)  1.3 KB
  
version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: Cx

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch
    steps:
      - checkout
 
      - run:
          name: Install CxCLI Plugin
          command: |
            wget -O ~/cxflow.jar https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.15/cx-flow-1.6.15.jar
 
 
      - run:
          name: Execute CxSAST Scan
          command: |
            java -jar cx-flow.jar  \
			  --spring.config.location="~/.checkmarx/application.yml"  \
			  --project  \
			  --cx-team="$CX_TEAM"  \
			  --cx-project="$CX_PROJECT"  \
			  --app="$CX_PROJECT"
			  

      - run:
          name: Moving Artifacts
          command: |
            mkdir ~/artifacts
            mv ~/cxcli/Checkmarx/Reports/* ~/artifacts
      # Store the generated reports with the build logs in CircleCI
      - store_artifacts:
          path: ~/artifacts
          destination: sast_results

