name: CheckmarxKICS
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  KICS:     
    runs-on: ubuntu-latest
    steps:
    - name: KICS Github Action
      uses: Checkmarx/kics-github-action@master
      with:
          path: "./"
          output_path: 'kics-results.json'
        
